name: Azure Pipeline
variables:
- group: customer1_vars
trigger:
- main

pool: 
 name: DevOps_Agent

stages:
- stage: CI
  jobs:
  - job: usenodeversion
    steps: 
    - task: CmdLine@2
      inputs:
        script: |
          echo Write your commands here  
          echo Hello world
          sudo apt install nodejs -y
          sudo apt-get install npm -y 
          sudo apt-get install yarn -y
          npm --version
          node --version
          yarn --version