name: Azure Pipeline
variables:
 - name: projectName
   value: customer1_vars
trigger:
 - master
pool:
 vmImage: 'ubuntu-latest'
steps:
- script: |
   node --version
   npm --version
   yarn --version
   pwd
   ls
   rm -rf dist
   rm -rf node_modules
   ls
- script: echo $(projectName)
   yarn
   yarn run dev --env.CLIENT_NAME=sfx
   pwd
   ls
   echo "Removing existing dev package directory"
   rm -rf dev
   ls
   echo "creating new dev package directory"
   mkdir dev
   cp -r dist ./dev 
   cp package.json server.js powerBi.js ./dev
   cp -r node_modules ./dev
   cp -r jumpcloud ./dev
   echo "Listing contents of New Environment"
   ls ./dev
  displayName: yarn name